### ISSUE TITLE
Trouble on installing 

### ISSUE THREAD

**Issue by ghost** [ovnworks/docker-ovn-driver#1]
Hey guys, before for that good job !

But when i tried to install make file options, i have got this error :

```
/bin/sh: 1: python: not found
Makefile:13: recipe for target 'test' failed
make: *** [test] Error 127
```

**Comment by greenpau** [comment]
```
Makefile:13: recipe for target 'test' failed
```

@ultron1995 , you would need to install `python` to make the test work.

If you just want to build the container, do the following.

1. Go to the below line and remove the word `test` from it.

https://github.com/ovnworks/docker-ovn-driver/blob/master/Makefile#L23

2. Run `make plugin`
